# Generated by Django 6.0.6 on 2026-08-15 20:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_cartaopartida_registrodisciplinaratleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração Principal', max_length=150)),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('intervalo_padrao_minutos', models.PositiveIntegerField(default=10, help_text='Tempo de intervalo para troca de times/aquecimento no mesmo recurso', verbose_name='Intervalo padrão de transição (minutos)')),
                ('descanso_minimo_equipe_minutos', models.PositiveIntegerField(default=60, help_text='Tempo mínimo de recuperação entre duas partidas de uma mesma delegação/equipe', verbose_name='Descanso mínimo entre jogos da mesma equipe (minutos)')),
                ('duracao_padrao_jogo_minutos', models.PositiveIntegerField(default=50, help_text='Duração estimada da partida caso a modalidade não possua duração específica', verbose_name='Duração padrão de jogo (minutos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Geral de Agendamento',
                'verbose_name_plural': 'Configurações Gerais de Agendamento',
            },
        ),
        migrations.CreateModel(
            name='CenarioExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Cronograma Gerado', max_length=150)),
                ('status', models.CharField(choices=[('sucesso', 'Viável (Sucesso)'), ('inviavel', 'Inviável (Conflitos Detectados)'), ('aplicado', 'Aplicado ao Calendário Oficial')], default='sucesso', max_length=20)),
                ('mensagem_diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico / Erros')),
                ('metricas', models.JSONField(blank=True, default=dict, verbose_name='Métricas da Alocação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='agendamento.configuracaogeral')),
            ],
            options={
                'verbose_name': 'Cenário de Agendamento',
                'verbose_name_plural': 'Cenários de Agendamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DataDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Competição')),
                ('horario_inicio', models.TimeField(default=datetime.time(8, 0), verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(default=datetime.time(22, 0), verbose_name='Horário Limite')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível?')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='agendamento.configuracaogeral')),
            ],
            options={
                'verbose_name': 'Data Disponível',
                'verbose_name_plural': 'Datas Disponíveis',
                'ordering': ['data'],
                'unique_together': {('configuracao', 'data')},
            },
        ),
        migrations.CreateModel(
            name='RecursoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Local/Recurso')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição/Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Prioridade')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='agendamento.configuracaogeral')),
                ('modalidades_permitidas', models.ManyToManyField(blank=True, help_text='Selecione as modalidades compatíveis. Se nenhuma for selecionada, o local aceitará qualquer modalidade.', related_name='recursos_locais_agendamento', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Recurso / Local de Jogo',
                'verbose_name_plural': 'Recursos / Locais de Jogos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_nome', models.CharField(max_length=100)),
                ('fase_codigo', models.CharField(max_length=50)),
                ('fase_display', models.CharField(max_length=100)),
                ('time_a_id', models.IntegerField(blank=True, null=True)),
                ('time_a_nome', models.CharField(default='A definir', max_length=150)),
                ('time_b_id', models.IntegerField(blank=True, null=True)),
                ('time_b_nome', models.CharField(default='A definir', max_length=150)),
                ('data_alocada', models.DateField(verbose_name='Data Alocada')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('recurso_nome', models.CharField(max_length=120)),
                ('status', models.CharField(default='alocado', max_length=20)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='agendamento.cenarioexecucao')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_agendador', to='core.jogo')),
                ('partida_chaveamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_agendador', to='core.partidachaveamento')),
                ('recurso_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='agendamento.recursolocal')),
            ],
            options={
                'verbose_name': 'Item de Alocação',
                'verbose_name_plural': 'Itens de Alocação',
                'ordering': ['data_alocada', 'horario_inicio', 'recurso_nome'],
            },
        ),
        migrations.CreateModel(
            name='RestricaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código da Fase')),
                ('fase_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome da Fase')),
                ('ordem_precedencia', models.PositiveIntegerField(default=0, help_text='Fases com ordem menor devem ocorrer antes de fases com ordem maior.', verbose_name='Ordem Lógica de Precedência')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_fases', to='agendamento.configuracaogeral')),
                ('datas_permitidas', models.ManyToManyField(blank=True, help_text='Se nenhuma data for selecionada, a fase poderá usar qualquer data geral da competição.', related_name='fases_restringidas', to='agendamento.datadisponivel', verbose_name='Datas Permitidas para esta Fase')),
                ('modalidade', models.ForeignKey(blank=True, help_text='Opcional: vincular a uma modalidade específica. Se vazio, aplica-se a todas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_fases_agendamento', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Restrição de Data por Fase',
                'verbose_name_plural': 'Restrições de Datas por Fases',
                'ordering': ['ordem_precedencia', 'fase_codigo'],
            },
        ),
        migrations.CreateModel(
            name='ParametroModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_minutos', models.PositiveIntegerField(default=50, verbose_name='Duração da Partida (minutos)')),
                ('intervalo_pos_jogo_minutos', models.PositiveIntegerField(default=10, verbose_name='Buffer/Intervalo Pós-Jogo (minutos)')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_modalidades', to='agendamento.configuracaogeral')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_agendamento', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Parâmetro por Modalidade',
                'verbose_name_plural': 'Parâmetros por Modalidade',
                'unique_together': {('configuracao', 'modalidade')},
            },
        ),
    ]
