# Generated by Django 6.0.6 on 2026-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='agrupar_modalidades_rede',
            field=models.BooleanField(default=True, help_text='Garante que jogos de voleibol aconteçam em sequência contínua no mesmo turno/dia para evitar montagens e desmontagens repetidas de rede', verbose_name='Agrupar Vôlei em bloco contínuo'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='max_jogos_diarios_por_equipe',
            field=models.PositiveIntegerField(default=2, help_text='Limite de partidas que uma mesma equipe/delegação pode disputar no mesmo dia para evitar desgaste excessivo', verbose_name='Máximo de jogos por dia por equipe'),
        ),
    ]
