# Generated by Django 6.0.6 on 2026-08-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_configuracaogeral_agrupar_modalidades_rede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='descanso_minimo_equipe_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Tempo mínimo de recuperação entre duas partidas de uma mesma equipe na mesma modalidade', verbose_name='Descanso mínimo entre jogos da mesma equipe (minutos)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='max_jogos_diarios_por_equipe',
            field=models.PositiveIntegerField(default=2, help_text='Limite de partidas que uma mesma equipe pode disputar no mesmo dia na mesma modalidade para evitar desgaste excessivo', verbose_name='Máximo de jogos por dia por equipe'),
        ),
    ]
