# Generated by Django 6.0.6 on 2026-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_configuracaogeral_descanso_minimo_equipe_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='turno_bloco_rede',
            field=models.CharField(choices=[('auto', 'Automático (Sistema escolhe o melhor turno - Máx. 1 turno por dia)'), ('manha', 'Somente Manhã (Restringir ao turno matutino)'), ('tarde', 'Somente Tarde / Noite (Restringir ao turno vespertino/noturno)'), ('integral', 'Livre / Integral (Sem limite de turno)')], default='auto', help_text='Define a restrição de turno para o bloco contínuo de voleibol: Automático (máx. 1 turno por dia), Somente Manhã, Somente Tarde/Noite ou Livre (dia todo)', max_length=20, verbose_name='Turno do Bloco de Vôlei/Rede'),
        ),
    ]
