# Generated by Django 6.0.6 on 2026-06-22 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Autorizado')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
            ],
            options={
                'verbose_name': 'Whitelist da Comissão',
                'verbose_name_plural': 'Whitelists da Comissão',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('foto_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL da Foto de Perfil')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google Subject ID')),
                ('role', models.CharField(choices=[('COMISSAO', 'Comissão Organizadora'), ('REPRESENTANTE', 'Representante de Delegação')], default='REPRESENTANTE', max_length=20, verbose_name='Papel de Acesso')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('nome_delegacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Delegação')),
                ('perfil_completo', models.BooleanField(default=False, verbose_name='Perfil Completado?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
