# Generated by Django 6.0.6 on 2026-06-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='justificativa_delegacao',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Delegação'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_delegacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Análise'), ('deferido', 'Deferido (Aprovado)'), ('indeferido', 'Indeferido (Recusado)')], default='pendente', max_length=20, verbose_name='Status da Delegação'),
        ),
    ]
