# Generated by Django 6.0.6 on 2026-06-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_justificativa_delegacao_user_status_delegacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_delegados', to=settings.AUTH_USER_MODEL, verbose_name='Delegado Principal'),
        ),
        migrations.CreateModel(
            name='MembroDelegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Autorizado')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('delegado_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Delegado Principal')),
            ],
            options={
                'verbose_name': 'Membro da Delegação',
                'verbose_name_plural': 'Membros da Delegação',
                'unique_together': {('delegado_principal', 'email')},
            },
        ),
    ]
