# Generated by Django 6.0.6 on 2026-07-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_parent_delegate_membrodelegacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='justificativa_pagamento',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa do Pagamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='link_comprovante_pagamento',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link do Comprovante de Pagamento Único'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_pagamento',
            field=models.CharField(choices=[('nao_avaliado', 'Não avaliado'), ('deferido', 'Deferido (Aprovado)'), ('indeferido', 'Indeferido (Recusado)')], default='nao_avaliado', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
