# Generated by Django 6.0.6 on 2026-07-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_justificativa_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscritosPorDelegacao',
            fields=[
            ],
            options={
                'verbose_name': 'Inscritos por Delegação',
                'verbose_name_plural': 'Inscritos por Delegações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
