# Generated by Django 6.0.6 on 2026-06-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não-binário')], default='M', max_length=1, verbose_name='Gênero')),
                ('link_documento', models.URLField(blank=True, help_text='Link para o documento de identificação (RG, CNH, etc.)', null=True)),
                ('is_egresso', models.BooleanField(default=False, help_text='Marque se o atleta for formado.', verbose_name='É egresso?')),
                ('link_documento_egresso', models.URLField(blank=True, help_text='Link obrigatório (Drive) caso seja egresso.', null=True)),
                ('em_conformidade', models.BooleanField(default=True, help_text='Define se o atleta cumpre todos os requisitos do regulamento')),
                ('justificativa_inconformidade', models.TextField(blank=True, help_text='Motivo pelo qual o atleta não está em conformidade', null=True)),
                ('permite_correcao', models.BooleanField(default=False, help_text='Se marcado, o representante pode enviar um novo documento')),
                ('link_correcao', models.URLField(blank=True, help_text='Novo documento enviado pelo representante para reavaliação', null=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_jogo', models.DateField(verbose_name='Data do Jogo')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local/Quadra')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Jogo Finalizado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Misto')], default='M', max_length=1, verbose_name='Gênero da Categoria')),
                ('limite_minimo_jogadores', models.PositiveIntegerField(default=1)),
                ('limite_maximo_jogadores', models.PositiveIntegerField(default=20)),
                ('inscricoes_abertas', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='PreSumula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pré-Súmula',
                'verbose_name_plural': 'Pré-Súmulas',
            },
        ),
        migrations.CreateModel(
            name='PreSumulaAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camisa', models.PositiveIntegerField(verbose_name='Número da Camisa')),
            ],
            options={
                'verbose_name': 'Atleta Escalado',
                'verbose_name_plural': 'Atletas Escalados',
            },
        ),
    ]
