# Generated by Django 6.0.6 on 2026-06-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite_minimo_jogadores', models.PositiveIntegerField(default=1)),
                ('limite_maximo_jogadores', models.PositiveIntegerField(default=20)),
                ('inscricoes_abertas', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=100)),
                ('link_comprovante', models.URLField(help_text='Link para o documento comprobatório (Google Drive, etc)')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('atletas', models.ManyToManyField(related_name='equipes', to='core.atleta')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_representadas', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
