# Generated by Django 6.0.6 on 2026-06-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jogo',
            name='delegacao_mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to=settings.AUTH_USER_MODEL, verbose_name='Delegação Mandante'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='delegacao_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to=settings.AUTH_USER_MODEL, verbose_name='Delegação Visitante'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.modalidade'),
        ),
        migrations.AddField(
            model_name='presumula',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presumulas', to='core.jogo'),
        ),
        migrations.AddField(
            model_name='presumula',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presumulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presumulaatleta',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes_jogos', to='core.atleta'),
        ),
        migrations.AddField(
            model_name='presumulaatleta',
            name='presumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacao', to='core.presumula'),
        ),
        migrations.AddField(
            model_name='presumula',
            name='atletas',
            field=models.ManyToManyField(related_name='presumulas_escaladas', through='core.PreSumulaAtleta', to='core.atleta'),
        ),
        migrations.AlterUniqueTogether(
            name='presumulaatleta',
            unique_together={('presumula', 'atleta')},
        ),
        migrations.AlterUniqueTogether(
            name='presumula',
            unique_together={('jogo', 'representante')},
        ),
    ]
