# Generated by Django 6.0.6 on 2026-06-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='horario_jogo',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do Jogo'),
        ),
    ]
