# Generated by Django 6.0.6 on 2026-06-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atleta_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Comentários da comissão em caso de não aprovação', null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
