# Generated by Django 6.0.6 on 2026-06-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jogo_horario_jogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='delegacao_mandante',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='delegacao_visitante',
        ),
        migrations.AddField(
            model_name='jogo',
            name='time_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_time_a', to=settings.AUTH_USER_MODEL, verbose_name='Time A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='time_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_time_b', to=settings.AUTH_USER_MODEL, verbose_name='Time B'),
            preserve_default=False,
        ),
    ]
