# Generated by Django 6.0.6 on 2026-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipe_justificativa_equipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='em_conformidade',
            field=models.BooleanField(default=True, help_text='Define se o atleta cumpre todos os requisitos do regulamento'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='justificativa_inconformidade',
            field=models.TextField(blank=True, help_text='Motivo pelo qual o atleta não está em conformidade', null=True),
        ),
    ]
