# Generated by Django 6.0.6 on 2026-06-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atleta_em_conformidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando aprovação de inscrição'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoInclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_comprovante', models.URLField(help_text='Link para o documento comprobatório específico deste atleta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.atleta')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.equipe')),
            ],
        ),
    ]
