# Generated by Django 6.0.6 on 2026-06-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_jogo_delegacao_mandante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, help_text='Se preenchido, a modalidade só ficará pública para inscrições a partir desta data/hora.', null=True, verbose_name='Data/Hora de Publicação (Agendamento)'),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Análise'), ('deferido', 'Deferido (Aprovado)'), ('indeferido', 'Indeferido (Recusado)')], default='pendente', max_length=20, verbose_name='Status da Inscrição')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('delegacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='InscricaoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atletas', models.ManyToManyField(related_name='modalidades_inscritas', to='core.atleta')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='core.inscricao')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Modalidade Inscrita',
                'verbose_name_plural': 'Modalidades Inscritas',
                'unique_together': {('inscricao', 'modalidade')},
            },
        ),
    ]
