# Generated by Django 6.0.6 on 2026-06-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_equipe_status_solicitacaoinclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='link_correcao',
            field=models.URLField(blank=True, help_text='Novo documento enviado pelo representante para reavaliação', null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='permite_correcao',
            field=models.BooleanField(default=False, help_text='Se marcado, o representante pode enviar um novo documento'),
        ),
    ]
