# Generated by Django 6.0.6 on 2026-06-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modalidade_data_publicacao_inscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='em_conformidade',
            field=models.BooleanField(default=False, help_text='Define se o atleta cumpre todos os requisitos do regulamento'),
        ),
    ]
