# Generated by Django 6.0.6 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atleta_link_correcao_atleta_permite_correcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='is_egresso',
            field=models.BooleanField(default=False, help_text='Marque se o atleta for formado.', verbose_name='É egresso?'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='link_documento_egresso',
            field=models.URLField(blank=True, help_text='Link obrigatório (Drive) caso seja egresso.', null=True),
        ),
    ]
