# Generated by Django 6.0.6 on 2026-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_atleta_em_conformidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='arbitro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Árbitro'),
        ),
        migrations.AddField(
            model_name='presumula',
            name='tecnico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnico da Partida'),
        ),
    ]
