# Generated by Django 6.0.6 on 2026-07-01 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jogo_arbitro_presumula_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Real do Jogo'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('corpo', models.TextField(verbose_name='Corpo do Recurso')),
                ('link_anexo', models.URLField(blank=True, null=True, verbose_name='Link para Anexo (Drive, etc.)')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('parecer_emitido', 'Parecer Emitido'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.jogo')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_interpostos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RecursoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.recurso')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem do Recurso',
                'verbose_name_plural': 'Mensagens dos Recursos',
                'ordering': ['data_envio'],
            },
        ),
    ]
