# Generated by Django 6.0.6 on 2026-07-01 13:55

import django.db.models.deletion
from django.db import migrations, models


def populate_campus_and_link(apps, schema_editor):
    Campus = apps.get_model('core', 'Campus')
    Atleta = apps.get_model('core', 'Atleta')

    # 1. Create the four mandatory campuses
    mandatory_campi = ["Campus Diamantina", "Campus Mucuri", "Campus Janaúba", "Campus Unaí"]
    campus_objs = {}
    for name in mandatory_campi:
        obj, created = Campus.objects.get_or_create(nome=name)
        campus_objs[name] = obj

    # 2. For each athlete, find/create the corresponding Campus and set it to campus_temp
    for atleta in Atleta.objects.all():
        old_name = atleta.campus
        if old_name:
            old_name_stripped = old_name.strip()
            if old_name_stripped:
                # Map old names or create new campus objects if they don't match
                if old_name_stripped not in campus_objs:
                    obj, created = Campus.objects.get_or_create(nome=old_name_stripped)
                    campus_objs[old_name_stripped] = obj
                atleta.campus_temp = campus_objs[old_name_stripped]
                atleta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jogo_data_hora_fim_notificacao_recurso_and_more'),
    ]

    operations = [
        # 1. Create Campus model
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        # 2. Add temporary field for ForeignKey
        migrations.AddField(
            model_name='atleta',
            name='campus_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.campus'),
        ),
        # 3. Populate new Field and Campus records
        migrations.RunPython(populate_campus_and_link, reverse_code=migrations.RunPython.noop),
        # 4. Remove old CharField
        migrations.RemoveField(
            model_name='atleta',
            name='campus',
        ),
        # 5. Rename temporary ForeignKey field to 'campus'
        migrations.RenameField(
            model_name='atleta',
            old_name='campus_temp',
            new_name='campus',
        ),
    ]
