# Generated by Django

from django.db import migrations


def merge_campuses(apps, schema_editor):
    Campus = apps.get_model('core', 'Campus')
    Atleta = apps.get_model('core', 'Atleta')

    # Ensure "Campus Diamantina" exists
    diamantina, _ = Campus.objects.get_or_create(nome="Campus Diamantina")

    # Merge athletes from legacy/duplicate Diamantina campuses into "Campus Diamantina"
    legacy_campi = Campus.objects.filter(nome__in=["Campus I", "Campus JK"])
    for campus in legacy_campi:
        Atleta.objects.filter(campus=campus).update(campus=diamantina)
        campus.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campus_alter_atleta_campus'),
    ]

    operations = [
        migrations.RunPython(merge_campuses, reverse_code=migrations.RunPython.noop),
    ]
