# Generated by Django 6.0.6 on 2026-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_diamantina_campuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='curso',
            field=models.CharField(max_length=100, verbose_name='Curso (estudante)/Lotação (servidor)'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Matrícula/SIAPE'),
        ),
    ]
