# Generated by Django 6.0.6 on 2026-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_atleta_curso_alter_atleta_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='tipo_atleta',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor/Técnico')], default='estudante', max_length=20, verbose_name='Tipo de Atleta'),
        ),
    ]
