# Generated by Django 6.0.6 on 2026-07-01 17:44

from django.db import migrations, models


def populate_status_avaliacao(apps, schema_editor):
    Atleta = apps.get_model('core', 'Atleta')
    for atleta in Atleta.objects.all():
        if atleta.em_conformidade:
            atleta.status_avaliacao = 'deferido'
        elif atleta.justificativa_inconformidade or atleta.permite_correcao or atleta.link_correcao:
            atleta.status_avaliacao = 'indeferido'
        else:
            atleta.status_avaliacao = 'nao_avaliado'
        atleta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atleta_tipo_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='status_avaliacao',
            field=models.CharField(choices=[('nao_avaliado', 'Não avaliado'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], default='nao_avaliado', max_length=20, verbose_name='Status da Avaliação'),
        ),
        migrations.RunPython(populate_status_avaliacao),
    ]

