# Generated by Django 6.0.6 on 2026-07-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_atleta_status_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='data_publicacao',
        ),
    ]
