# Generated by Django 6.0.6 on 2026-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_modalidade_data_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPeriodoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora de Início das Inscrições')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora de Fim das Inscrições')),
            ],
            options={
                'verbose_name': 'Configuração do Período de Inscrição',
                'verbose_name_plural': 'Configurações do Período de Inscrição',
            },
        ),
    ]
