# Generated by Django 6.0.6 on 2026-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracaoperiodoinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoperiodoinscricao',
            name='segunda_chamada_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fim da Segunda Chamada'),
        ),
        migrations.AddField(
            model_name='configuracaoperiodoinscricao',
            name='segunda_chamada_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Início da Segunda Chamada'),
        ),
    ]
