# Generated by Django 6.0.6 on 2026-07-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracaoperiodoinscricao_segunda_chamada_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituicaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_substituicao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Substituição')),
                ('atleta_entrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutos', to='core.atleta')),
                ('atleta_saiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituidos', to='core.atleta')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='core.inscricao')),
            ],
            options={
                'verbose_name': 'Substituição de Atleta',
                'verbose_name_plural': 'Substituições de Atletas',
            },
        ),
    ]
