# Generated by Django 6.0.6 on 2026-07-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_substituicaoatleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='placar_time_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Placar Time A'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='placar_time_b',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Placar Time B'),
        ),
        migrations.CreateModel(
            name='ChaveamentoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_atual', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('fase_grupos', 'Fase de Grupos / Classificatórias'), ('mata_mata_local', 'Mata-Mata Local (Diamantina)'), ('fase_geral', 'Semifinais e Finais Gerais'), ('finalizado', 'Torneio Finalizado')], default='nao_iniciado', max_length=30)),
                ('vagas_externas', models.PositiveIntegerField(default=0, help_text='Total de vagas classificadas dos campi externos (0, 1 ou 2)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modalidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chaveamento', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Chaveamento de Modalidade',
                'verbose_name_plural': 'Chaveamentos de Modalidades',
            },
        ),
        migrations.CreateModel(
            name='GrupoChaveamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('grupo_local', 'Grupo Sede (Diamantina)'), ('eliminatoria_ext', 'Eliminatória Externa')], default='grupo_local', max_length=20)),
                ('vagas_classificacao', models.PositiveIntegerField(default=2)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus')),
                ('chaveamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.chaveamentomodalidade')),
            ],
            options={
                'verbose_name': 'Grupo de Chaveamento',
                'verbose_name_plural': 'Grupos de Chaveamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PartidaChaveamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('EXTERNO_ELIMINATORIA', 'Eliminatória Externa'), ('GRUPO_LOCAL', 'Fase de Grupos'), ('QUARTAS_LOCAL', 'Quartas de Final (Diamantina)'), ('SEMI_LOCAL', 'Semifinal (Diamantina)'), ('FINAL_LOCAL', 'Final (Diamantina)'), ('DISPUTA_3_LOCAL', '3º Lugar (Diamantina)'), ('SEMI_GERAL', 'Semifinal Geral'), ('FINAL_GERAL', 'Final Geral'), ('BRONZE', 'Chave Bronze (3º Lugar Geral)')], max_length=30)),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('placar_a', models.PositiveIntegerField(blank=True, null=True)),
                ('placar_b', models.PositiveIntegerField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('posicao_proxima_partida', models.CharField(blank=True, choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1, null=True)),
                ('posicao_perdedor_destino', models.CharField(blank=True, choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1, null=True)),
                ('chaveamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.chaveamentomodalidade')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='core.grupochaveamento')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_chaveamento', to='core.jogo')),
                ('partida_perdedor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_origem_perdedor', to='core.partidachaveamento')),
                ('perdedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_perdidas', to=settings.AUTH_USER_MODEL)),
                ('proxima_partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_origem', to='core.partidachaveamento')),
                ('time_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_chaveamento_a', to=settings.AUTH_USER_MODEL)),
                ('time_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_chaveamento_b', to=settings.AUTH_USER_MODEL)),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_vencidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida do Chaveamento',
                'verbose_name_plural': 'Partidas do Chaveamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('classificado', models.BooleanField(default=False)),
                ('delegacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_chaveamento', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.grupochaveamento')),
            ],
            options={
                'verbose_name': 'Time no Grupo',
                'verbose_name_plural': 'Times nos Grupos',
                'ordering': ['-pontos', '-vitorias', '-saldo_gols', '-gols_pro'],
                'unique_together': {('grupo', 'delegacao')},
            },
        ),
    ]
