# Generated by Django 6.0.6 on 2026-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jogo_placar_time_a_jogo_placar_time_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaveamentomodalidade',
            name='fase_atual',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('fase_grupos', 'Fase de Grupos / Classificatórias'), ('mata_mata_local', 'Mata-Mata Local (Diamantina)'), ('fase_geral', 'Semifinais e Finais Gerais'), ('finalizado', 'Torneio Finalizado')], db_index=True, default='nao_iniciado', max_length=30),
        ),
        migrations.AlterField(
            model_name='partidachaveamento',
            name='fase',
            field=models.CharField(choices=[('EXTERNO_ELIMINATORIA', 'Eliminatória Externa'), ('GRUPO_LOCAL', 'Fase de Grupos'), ('QUARTAS_LOCAL', 'Quartas de Final (Diamantina)'), ('SEMI_LOCAL', 'Semifinal (Diamantina)'), ('FINAL_LOCAL', 'Final (Diamantina)'), ('DISPUTA_3_LOCAL', '3º Lugar (Diamantina)'), ('SEMI_GERAL', 'Semifinal Geral'), ('FINAL_GERAL', 'Final Geral'), ('BRONZE', 'Chave Bronze (3º Lugar Geral)')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='partidachaveamento',
            name='finalizada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='timegrupo',
            name='classificado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
