# Generated by Django 6.0.6 on 2026-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_chaveamentomodalidade_fase_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaveamentomodalidade',
            name='datas_fases',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento de datas por fase do chaveamento'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='data_partida',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Partida'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='horario_partida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Partida'),
        ),
    ]
