# Generated by Django 6.0.6 on 2026-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chaveamentomodalidade_datas_fases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaveamentomodalidade',
            name='fase_atual',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('fase_grupos', 'Fase de Grupos / Classificatórias'), ('mata_mata_local', 'Mata-Mata Local (Diamantina)'), ('fase_geral', 'Ativo'), ('finalizado', 'Torneio Finalizado')], db_index=True, default='nao_iniciado', max_length=30),
        ),
    ]
