# Generated by Django 6.0.6 on 2026-08-10 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_chaveamentomodalidade_fase_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARELO', 'Cartão Amarelo'), ('SEGUNDO_AMARELO', 'Segundo Amarelo (Expulsão)'), ('VERMELHO', 'Cartão Vermelho Direto')], max_length=20)),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_partida', to='core.atleta')),
                ('delegacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_recebidos', to=settings.AUTH_USER_MODEL)),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.jogo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.modalidade')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.partidachaveamento')),
            ],
            options={
                'verbose_name': 'Cartão de Partida',
                'verbose_name_plural': 'Cartões de Partidas',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDisciplinarAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoes_amarelos_acumulados', models.PositiveIntegerField(default=0, help_text='Amarelos ativos para acúmulo')),
                ('suspenso_jogos_pendentes', models.PositiveIntegerField(default=0, help_text='Jogos de suspensão pendentes de cumprimento')),
                ('total_amarelos_historico', models.PositiveIntegerField(default=0)),
                ('total_vermelhos_historico', models.PositiveIntegerField(default=0)),
                ('total_jogos_suspensao_cumpridos', models.PositiveIntegerField(default=0)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_disciplinares', to='core.atleta')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_disciplinares_atletas', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Registro Disciplinar do Atleta',
                'verbose_name_plural': 'Registros Disciplinares dos Atletas',
                'unique_together': {('atleta', 'modalidade')},
            },
        ),
    ]
