# Generated by Django 6.0.6 on 2026-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cartaopartida_registrodisciplinaratleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='formato_chaveamento',
            field=models.CharField(choices=[('padrao', 'Padrão (Fase de Grupos + Mata-Mata Geral)'), ('formato_3_grupos_melhor_segundo', '3 Grupos de 3 (Melhor 2º Colocado Geral para Semifinais)')], default='padrao', help_text='Configuração do formato de chaveamento para a modalidade.', max_length=50, verbose_name='Formato de Chaveamento'),
        ),
    ]
