# Generated by Django 6.0.6 on 2026-08-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_modalidade_formato_chaveamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
