# Generated by Django 6.0.6 on 2026-08-17 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_atleta_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
