# Generated by Django 6.0.6 on 2026-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sync_segunda_chamada_atletas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='motivo_wo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do W.O.'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='wo_tipo',
            field=models.CharField(blank=True, choices=[('', 'Sem W.O.'), ('TIME_A', 'W.O. Time A'), ('TIME_B', 'W.O. Time B'), ('AMBOS', 'W.O. Ambos os Times')], default='', max_length=10, verbose_name='Tipo de W.O.'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='motivo_wo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do W.O.'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='wo_tipo',
            field=models.CharField(blank=True, choices=[('', 'Sem W.O.'), ('TIME_A', 'W.O. Time A'), ('TIME_B', 'W.O. Time B'), ('AMBOS', 'W.O. Ambos os Times')], default='', max_length=10, verbose_name='Tipo de W.O.'),
        ),
        migrations.AddField(
            model_name='timegrupo',
            name='quantidade_wo',
            field=models.IntegerField(default=0, verbose_name='Quantidade de W.O.'),
        ),
    ]
