# Generated by Django 6.0.6 on 2026-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_jogo_motivo_wo_jogo_wo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='permitir_lancamento_atletas',
            field=models.BooleanField(default=False, help_text='Permite que as delegações lancem/escalem atletas mesmo após o encerramento do prazo regulamentar.', verbose_name='Permitir Lançar Atletas'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='permitir_lancamento_atletas',
            field=models.BooleanField(default=False, help_text='Permite que as delegações lancem/escalem atletas mesmo após o encerramento do prazo regulamentar.', verbose_name='Permitir Lançar Atletas'),
        ),
    ]
