# Generated by Django 6.0.6 on 2026-09-06 16:14

from django.db import migrations, models


def atualizar_dados_substituicoes(apps, schema_editor):
    SubstituicaoAtleta = apps.get_model('core', 'SubstituicaoAtleta')
    PreSumulaAtleta = apps.get_model('core', 'PreSumulaAtleta')

    for sub in SubstituicaoAtleta.objects.all():
        sai = sub.atleta_saiu
        entra = sub.atleta_entrou

        if sai:
            sai.em_conformidade = False
            sai.status_avaliacao = 'substituido'
            sai.save(update_fields=['em_conformidade', 'status_avaliacao'])

        if entra:
            entra.em_conformidade = True
            entra.status_avaliacao = 'deferido'
            entra.save(update_fields=['em_conformidade', 'status_avaliacao'])

        if sub.inscricao:
            for im in sub.inscricao.modalidades.all():
                if sai:
                    im.atletas.remove(sai)
                if entra:
                    im.atletas.add(entra)

        if sai and entra:
            PreSumulaAtleta.objects.filter(
                atleta=sai,
                presumula__jogo__status__in=['agendado', 'em_andamento']
            ).update(atleta=entra)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_atualizar_cruzamento_mata_mata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='status_avaliacao',
            field=models.CharField(choices=[('nao_avaliado', 'Não avaliado'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido'), ('substituido', 'Substituído')], default='nao_avaliado', max_length=20, verbose_name='Status da Avaliação'),
        ),
        migrations.RunPython(atualizar_dados_substituicoes, reverse_code=migrations.RunPython.noop),
    ]

