# Generated by Django 6.0.6 on 2026-09-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_atualizar_atletas_substituidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timegrupo',
            options={'ordering': ['quantidade_wo', '-pontos', '-vitorias', '-saldo_gols', '-gols_pro'], 'verbose_name': 'Time no Grupo', 'verbose_name_plural': 'Times nos Grupos'},
        ),
    ]
