# Generated by Django 6.0.6 on 2026-09-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_timegrupo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidachaveamento',
            name='definicao_manual',
            field=models.BooleanField(default=False, help_text='Indica se as equipes foram selecionadas manualmente pela organização, impedindo substituição automática.', verbose_name='Definição Manual de Equipes'),
        ),
    ]
