# Generated by Django 6.0.6 on 2026-09-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class SafeCreateModel(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return

        with schema_editor.connection.cursor() as cursor:
            tables = schema_editor.connection.introspection.table_names(cursor)

        if model._meta.db_table not in tables:
            schema_editor.create_model(model)
        else:
            with schema_editor.connection.cursor() as cursor:
                existing_cols = {
                    col.name
                    for col in schema_editor.connection.introspection.get_table_description(
                        cursor, model._meta.db_table
                    )
                }
            for field in model._meta.fields:
                if field.column not in existing_cols:
                    schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_partidachaveamento_definicao_manual'),
    ]

    operations = [
        SafeCreateModel(
            name='SetPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.PositiveIntegerField(default=1, verbose_name='Número do Set')),
                ('pontos_a', models.PositiveIntegerField(default=0, verbose_name='Pontos Time A')),
                ('pontos_b', models.PositiveIntegerField(default=0, verbose_name='Pontos Time B')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.jogo')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.partidachaveamento')),
            ],
            options={
                'verbose_name': 'Set da Partida',
                'verbose_name_plural': 'Sets da Partida',
                'ordering': ['numero_set', 'id'],
            },
        ),
    ]
