# Generated by Django 6.0.6 on 2026-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_setpartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='link_pre_sumula',
            field=models.URLField(blank=True, help_text='Link externo ou documento da pré-súmula da partida.', max_length=500, null=True, verbose_name='Link da Pré-Súmula'),
        ),
        migrations.AddField(
            model_name='partidachaveamento',
            name='link_pre_sumula',
            field=models.URLField(blank=True, help_text='Link externo ou documento da pré-súmula da partida.', max_length=500, null=True, verbose_name='Link da Pré-Súmula'),
        ),
    ]
