# Generated by Django 6.0.6 on 2026-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_jogo_link_pre_sumula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='link_pre_sumula',
            field=models.URLField(blank=True, help_text='Link externo ou documento da súmula da partida.', max_length=500, null=True, verbose_name='Link da Súmula'),
        ),
        migrations.AlterField(
            model_name='partidachaveamento',
            name='link_pre_sumula',
            field=models.URLField(blank=True, help_text='Link externo ou documento da súmula da partida.', max_length=500, null=True, verbose_name='Link da Súmula'),
        ),
    ]
