# Generated by Django 6.0.6 on 2026-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_jogo_link_pre_sumula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaveamentomodalidade',
            name='fases_iniciais',
            field=models.JSONField(blank=True, default=list, help_text="Lista de fases iniciais (ex: [{'numero': 1, 'nome': 'Fase 1'}, ...])"),
        ),
        migrations.AddField(
            model_name='grupochaveamento',
            name='fase_numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número da Fase'),
        ),
    ]
