# Generated by Django 6.0.6 on 2026-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_chaveamentomodalidade_fases_iniciais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidachaveamento',
            name='tipo_classificacao',
            field=models.CharField(choices=[('AUTOMATICO', 'Automático (Pelo Placar)'), ('AMBOS', 'Ambos Classificados (Avanço Duplo)'), ('TIME_A', 'Apenas Time A Classificado'), ('TIME_B', 'Apenas Time B Classificado'), ('NENHUM', 'Nenhum Classificado (Eliminação Mútua)')], default='AUTOMATICO', help_text='Define quem avança de fase: automático pelo placar, ambos os times, apenas um ou nenhum.', max_length=20, verbose_name='Critério de Classificação'),
        ),
    ]
