# Generated by Django 6.0.6 on 2026-08-07 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_alter_chaveamentomodalidade_fase_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefeicaoAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Refeição')),
                ('tipo', models.CharField(choices=[('cafe', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar')], max_length=20, verbose_name='Tipo de Refeição')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição / Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo para Validação?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campi_liberados', models.ManyToManyField(related_name='refeicoes_liberadas', to='core.campus', verbose_name='Campi Liberados')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refeição Agendada',
                'verbose_name_plural': 'Refeições Agendadas',
                'ordering': ['-data', 'tipo'],
                'unique_together': {('data', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Retirada')),
                ('metodo_validacao', models.CharField(choices=[('qrcode', 'QR Code'), ('manual', 'Busca Manual')], default='qrcode', max_length=10, verbose_name='Método de Validação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_refeicao', to='core.atleta', verbose_name='Atleta')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='refeicoes.refeicaoagendada', verbose_name='Refeição Agendada')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Registro de Retirada de Refeição',
                'verbose_name_plural': 'Registros de Retirada de Refeição',
                'ordering': ['-data_retirada'],
                'unique_together': {('refeicao', 'atleta')},
            },
        ),
    ]
