# Generated by Django 6.0.6 on 2026-08-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrorefeicao',
            name='metodo_validacao',
        ),
    ]
