# Generated by Django 6.0.6 on 2026-08-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_remove_registrorefeicao_metodo_validacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicaoagendada',
            name='descricao',
        ),
    ]
