# Generated by Django 6.0.6 on 2026-09-08 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atleta', 'Atletas'), ('comissao', 'Comissão Organizadora')], max_length=20, verbose_name='Tipo de Declaração')),
                ('total_documentos', models.PositiveIntegerField(default=0, verbose_name='Total de Documentos')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('periodo', models.CharField(max_length=255, verbose_name='Período')),
                ('cidade_data', models.CharField(max_length=255, verbose_name='Cidade e Data')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
            ],
            options={
                'verbose_name': 'Histórico de Emissão',
                'verbose_name_plural': 'Históricos de Emissões',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='MembroComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, help_text='Número de matrícula ou SIAPE institucional', max_length=50, null=True, verbose_name='Matrícula / SIAPE')),
                ('cargo', models.CharField(default='Organizador', help_text='Ex: Organizador, Coordenador de Modalidade, Apoio Técnico', max_length=100, verbose_name='Papel / Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaracoes_comissao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Vinculado')),
            ],
            options={
                'verbose_name': 'Membro da Comissão',
                'verbose_name_plural': 'Membros da Comissão',
                'ordering': ['nome_completo'],
            },
        ),
    ]
